### ISSUE TITLE
Add Frontline CPC support options

### ISSUE THREAD

**Issue by Neckross** [Windows365Management/PSCloudPC#16]
Great work on this module!

It will be great to see support for Frontline CPCs (eg. PowerState)

Also, adding additional -switches (eg. Filter, SearchString, etc..) will be helpful.

Definitely PSCloudPC module is helping the community!

[AB#94](https://dev.azure.com/dingemanse/afa2a767-071a-4086-a89a-cf3b75cd4bb4/_workitems/edit/94)

**Comment by Windows365Management** [comment]
Hi Juan,

Thanks for your feedback, we are working on the support for Frontline!

Can you explain the additional switches? For which cmdlets, what kind of filters do you want to apply?

Again, thank you for your feedback Juan

Stefan

**Comment by Ruthhl3ss** [comment]
Hi Juan,

We have added support for frontline 1.0.8.

Thanks :-)

Niels
