### ISSUE TITLE
🚀 [Feature Request]: Support Frontline Service Plan

### ISSUE THREAD

**Issue by Windows365Management** [Windows365Management/PSCloudPC#36]
### Contact Details

PSCloudPC

### Feature

No

### Feature Description

Support the new cloudPcFrontLineServicePlan resource type.

| Property    | Type   | Description                                                                                                                  |
| ----------- | ------ | ---------------------------------------------------------------------------------------------------------------------------- |
| displayName | String | The display name of the front-line service plan. For example, `2vCPU/8GB/128GB Front-line` or `4vCPU/16GB/256GB Front-line`. |
| id          | String | The unique identifier (ID) of the front-line service plan.                                                                   |
| totalCount  | Int32  | The total number of front-line service plans purchased by the customer.                                                      |
| usedCount   | Int32  | The number of service plans that have been used for the account.                                                             |

### Feature Output

Get-CPCFrontLineServicePlan

**Comment by Ruthhl3ss** [comment]
This feature should be renamed. It is already possible to find the SKUs but the assigned licenses should also work for the regular service plans.

**Comment by Ruthhl3ss** [comment]
Get-CPCServicePlan Already supports this feature:

![image](https://github.com/user-attachments/assets/d4731b0d-271c-4893-bd2a-5f31ab1f4655)
