### ISSUE TITLE
🚀 [Feature Request]: Support rebooting CPC

### ISSUE THREAD

**Issue by StefanDingemanse** [Windows365Management/PSCloudPC#42]
### Contact Details

mail@stefandingemanse.com

### Feature

Add support for rebooting Cloud PC's

### Feature Description

New cmdlet for rebooting Cloud PC's. This cmdlet will accept input from pipeline so it can be used to pipe results from a get-cpc to reboot multiple cloud PC's.

### Feature Output

Invoke-CPCReboot

**Comment by Ruthhl3ss** [comment]
Added pull request: https://github.com/Windows365Management/PSCloudPC/pull/45
