### ISSUE TITLE
🪲[Bug]: Connect-Windows365 Logs in with my Main Account Instead of Demo Tenant Account

### ISSUE THREAD

**Issue by schmittnieto** [Windows365Management/PSCloudPC#58]
### Contact Details

cristian@schmitt-nieto.com

### What happened?

I used the `Connect-Windows365 -DeviceCode:$true -TenantID daeedbaf-XXXX-XXXX-XXXX-3139fefXXXXXXX` command to connect to our demo tenant. Although the device code is generated correctly, when I attempt to log in using the demo tenant account, it only allows me to "activate Graph." Subsequently, a new window opens and logs me in with my main account due to the device's Single Sign-On (SSO) settings. I expected to be able to log in with the demo tenant account without being redirected to my main account.

I talk about this issue with Stefan and he advised me to report it here 😊

Additional Information:
```
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...} 
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Steps to reproduce?

1. Open PowerShell.
2. Run the command: `Connect-Windows365 -DeviceCode:$true -TenantID daeedbaf-XXXX-XXXX-XXXX-3139fefXXXXXXX`
3. Note the device code displayed in the console.
4. Open the provided URL in a browser and enter the device code.
5. Attempt to log in using the demo tenant account.
6. Observe that only "activate Graph" is available and after activation, a new window opens logging in with the main account instead.

### Relevant log output
```
VERBOSE: Requested HTTP/1.1 POST with 332-byte payload
VERBOSE: Received HTTP/1.1 4358-byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: Completed Authentication
VERBOSE: Using Authentication Type: Interactive
VERBOSE: Using Windows Powershell Core, continue with the script
VERBOSE: Use Interactive Authentication
VERBOSE: Using Windows Powershell
```
_No response_

**Comment by Ruthhl3ss** [comment]
Hi Cristian,

Thanks for message. I have created a branche and will check this out on monday. For now, it's the easiest to use the previous version 1.0.12 .

I will fix this as soon as I can.

Thanks,
Niels

**Comment by Ruthhl3ss** [comment]
@schmittnieto I completely overhauled the authentication CMDlet and based it on MSAL.PS.

I have let go of wanting to do it by myself.

Can you test this? There is branche called the bug name where you can download the latest code. I have already tested all 4 methods and they work but I want to make sure they also work for you.

**Comment by schmittnieto** [comment]
Hi @Ruthhl3ss ,

it´s working right now: 
``` powershell
connect-Windows365 -DeviceCode:$true -verbose
VERBOSE: Setting profile as beta...
VERBOSE: Using Authentication Type: DeviceCode
VERBOSE: Using Device Code Authentication
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXX to authenticate.
```

``` powershell
Get-CloudPC                                                            in pwsh at 17:08:46

id                     : e813abed-XXXXXXX-dee6eb
managedDeviceName      : WVM-XXXXXX-F5VYS
managedDeviceId        : XXXXXX-60e5a728a34b
displayName            : Windows 365 Win11 23H2 - XXXXXXXX
userPrincipalName      : XXXXXXXXXXXX
status                 : provisioned
provisioningPolicyName : Windows 365 Win11 23H2
imageDisplayName       : Windows 11 Enterprise + Microsoft 365 Apps 23H2
lastmodifiedDateTime   : XXXXXX.2024 
serviceplanType        : enterprise
servicePlanName        : Cloud PC Enterprise 4vCPU/16GB/128GB
```

Thank you one more time! 🤗
